development:
  adapter: postgresql
  encoding: unicode
  database: RubyAngel_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: RubyAngel_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: RubyAngel_production
  pool: 5
  username: postgres
  password:
